version: '3'
services:

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
      - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./etc/nginx/logs:/var/log/nginx"
      - "./etc/ssl:/etc/ssl"
      - "./web:/var/www/html"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - php81
      - mysql
      - redis

  php81:
    container_name: php81
    build:
      context: ./etc/php81
    restart: always
    volumes:
      - "./etc/php81/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./etc/php81/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "./web:/var/www/html"
    ports:
      - "9081:9081"
    depends_on:
      - mysql
      - redis

  mysql:
    container_name: mysql
    image: mysql:8.0.1
    restart: always
    volumes:
      - "./etc/data/mysql:/var/lib/mysql"
    env_file:
      - ".env"
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"

  redis:
    container_name: redis
    image: redis
    restart: always
    volumes:
      - "./etc/data/redis:/data"
    ports:
      - "6379:6379"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "2083:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    restart: always
    depends_on:
      - mysql

  phpredisadmin:
    container_name: phpredisadmin
    image: erikdubbelboer/phpredisadmin
    ports:
      - "2084:80"
    environment:
      - ADMIN_USER=${REDIS_ADMIN_USER}
      - ADMIN_PASS=${REDIS_ADMIN_PASS}
      - REDIS_1_HOST=${REDIS_REDIS_1_HOST}
      - REDIS_1_PORT=${REDIS_REDIS_1_PORT}
    depends_on:
      - redis